baseURL = "/"
languageCode = "en-us"
title = "Robert's blog"
theme = "hugo-traveler"
SectionPagesMenu = "main"
Paginate = 10

[params]
   RSSEnabled = true
   ShowCopyright = true
   Description = "This is my little corner of the Internet. Enjoy!"

[author]
   Handle = "rmrobinson"
   FirstName = "Robert"
   LastName = "Robinson"
   Location = "Kitchener, ON"
   AboutPage = "/about"

[[menu.main]]
	name = "Trips"
	weight = 2
	identifier = "trips"
	url = "/trips/"

[[menu.main]]
	name = "About"
	weight = 3
	identifier = "about"
	url = "/about"
